# Generated by Django 3.0.3 on 2020-02-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0006_auto_20200226_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=400)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='banks.BloodGroup')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='banks.State')),
            ],
        ),
    ]
